#!/bin/bash

# Get geometry of waybar
geometry=$(swaymsg -t get_tree | jq -r '.. | select(.name? and .name == "waybar") | .rect | "\(.x),\(.y),\(.width),\(.height)"')

wofi --show drun --width 200 --height 300 --x 10 --y 8
