-- ~/.config/nvim/lua/plugins/init.lua
return {
  require("plugins.animation"),
  require("plugins.auto-session"),
  require("plugins.blackbeard"),
  require("plugins.bufferline"),
  require("plugins.cmp"),
  require("plugins.colorizer"),
  require("plugins.dashboard"),
  require("plugins.dressing"),
  require("plugins.formatter"),
  require("plugins.gitsigns"),
  require("plugins.hlslens"),
  require("plugins.lualine"),
  require("plugins.lsp-config"),
  require("plugins.mini"),
  require("plugins.neotree"),
  require("plugins.noice"),
  require("plugins.plenary"),
  require("plugins.scrollbar"),
  --require("plugins.spotify"),
  require("plugins.telescope"),
  require("plugins.todo-comments"),
  require("plugins.treesitter"),
  require("plugins.which-key"),
}
